name: Frontend CI

on:
  push:
    branches:
      - test-development
  pull_request:
    branches:
      - test-development

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
    
    - name: Build the project
      run: expo build:android --no-publish --non-interactive

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: expo-build
        path: ./path/to/your/build/artifacts
