name: Frontend CI

on:
    push:
        branches:
            - main
        paths:
            - 'VitaApp/**'
    pull_request:
        branches:
            - main
        paths:
            - 'VitaApp/**'

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Change directory to VitaApp
              run: cd VitaApp

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test:ci
